<a href="https://colab.research.google.com/github/sanaomaro/AIM-5001/blob/main/S_OmarM6_assn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

**QUESTION 7**

In [ ]:

# supress scientific notation
np.set_printoptions(suppress = True)
# read the data file from GitHub and convert to a NumPy ndarray object
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below
# with a link to the “raw” version of the file you pushed to your online GitHub repository
nyc_water = pd.read_csv("https://raw.githubusercontent.com/sanaomaro/AIM-5001/main/M6_Data.csv").to_numpy()
# verify you have an ndarray object
type(nyc_water)


numpy.ndarray

In [ ]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

In [ ]:
nyc_water.shape

(39, 4)

**What is the maximum yearly NYC consumption of water in millions of gallons per day?**

In [ ]:
nyc_water[:,2]

array([1512. , 1506. , 1309. , 1382. , 1424. , 1465. , 1326. , 1351. ,
       1447. , 1484. , 1402. , 1424. , 1469. , 1369. , 1368.5, 1357.7,
       1325.7, 1297.9, 1205.5, 1219.5, 1237.2, 1240.4, 1184. , 1135.6,
       1093.7, 1099.5, 1138. , 1069. , 1114. , 1098. , 1007.5, 1039. ,
       1021. , 1009.1, 1006.1,  996. , 1009. , 1002. ,  990.2])

In [ ]:
#our data is in the the third colummn , we slice the column and apply max function
nyc_water[:,2].max()

1512.0

**How many calendar years are represented within this data set? NumPy's shape command is one way to find 
out**

In [ ]:
nyc_water.shape
#the solution is 39

(39, 4)

In [ ]:
nyc_water[:,0]

array([1979., 1980., 1981., 1982., 1983., 1984., 1985., 1986., 1987.,
       1988., 1989., 1990., 1991., 1992., 1993., 1994., 1995., 1996.,
       1997., 1998., 1999., 2000., 2001., 2002., 2003., 2004., 2005.,
       2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013., 2014.,
       2015., 2016., 2017.])

In [ ]:
years = nyc_water[:,0]
years

array([1979., 1980., 1981., 1982., 1983., 1984., 1985., 1986., 1987.,
       1988., 1989., 1990., 1991., 1992., 1993., 1994., 1995., 1996.,
       1997., 1998., 1999., 2000., 2001., 2002., 2003., 2004., 2005.,
       2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013., 2014.,
       2015., 2016., 2017.])

In [ ]:
#trying to count a specific column for non zero values of years
np.count_nonzero(years)

39

**What is the mean and the standard deviation of the per capita daily water consumption?**

In [ ]:
nyc_water[:,3]

array([213., 213., 185., 194., 198., 203., 182., 185., 197., 202., 191.,
       194., 199., 184., 182., 179., 174., 169., 155., 155., 156., 155.,
       148., 141., 136., 136., 141., 132., 137., 135., 123., 127., 123.,
       121., 119., 118., 118., 117., 115.])

In [ ]:
#the mean
nyc_water[:,3].mean()

160.30769230769232

In [ ]:
nyc_water.size

156

In [ ]:
# we use the standard deviation function of numpy array, which is here another numby array of size 4
print(np.std(nyc_water, axis=0))
sd = np.std(nyc_water, axis=0)
type(sd)

[    11.25462868 470923.52098422    172.46702157     31.5189433 ]


numpy.ndarray

In [ ]:
sd.shape

(4,)

In [ ]:
nyc_water[:,3]

array([213., 213., 185., 194., 198., 203., 182., 185., 197., 202., 191.,
       194., 199., 184., 182., 179., 174., 169., 155., 155., 156., 155.,
       148., 141., 136., 136., 141., 132., 137., 135., 123., 127., 123.,
       121., 119., 118., 118., 117., 115.])

In [ ]:
#applying std directly to the specific column
np.std(nyc_water[:,3])

31.51894330370624

In [ ]:
#the standard deviation out of the array sd
sd[3]

31.51894330370624

In [ ]:
len(nyc_water)

39

**What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array 
of differences and save that to a variable called "pop_diff", then print that variable to the screen.**

In [ ]:
#our population colum is the second one
nyc_water[:,1]

array([7102100. , 7071639. , 7089241. , 7109105. , 7181224. , 7234514. ,
       7274054. , 7319246. , 7342476. , 7353719. , 7344175. , 7335650. ,
       7374501. , 7428944. , 7506166. , 7570458. , 7633040. , 7697812. ,
       7773443. , 7858259. , 7947660. , 8008278. , 8024963.5, 8041649. ,
       8058334.5, 8075020. , 8091705.5, 8108391. , 8125076.5, 8141762. ,
       8158447.5, 8175133. , 8284098. , 8361179. , 8422460. , 8471990. ,
       8516502. , 8537673. , 8622698. ])

In [ ]:
pop_diff = np.diff(nyc_water[:,1])
pop_diff
#some diffrences are by minus which means a decreasing in the popolation has happened

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])

**QUESTION 1**

**Finding Intersection with no repetition**

In [ ]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(np.intersect1d(a, b))

[2 4]


**QUESTION 2**

**Creating and Converting 1d to 2d array using sequencing which Is linspace**

In [ ]:
arr = np.linspace(start = 1, stop = 15, num = 15, dtype ="int") #linspace makes array according to start stop and number of values
print(arr)
#reshape to make it 2d
arrr = np.reshape(arr,(5,3), order='F') #Fortran like order which is a column wise order
print(arrr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [ ]:
#attempt just for confirmation on slicing
arr1 = np.array([[23,67],[78,92]])
print(arr1)
arr1[1,0]
arr1.shape

[[23 67]
 [78 92]]


(2, 2)

**QUESTION 3**

**Flettening, three ways**

In [ ]:
#using flatten method with Fortran like order
res = arrr.flatten(order ='F')
print(res)
print(res.shape)
print(arrr)
arrr.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


(5, 3)

In [ ]:
#using ravel method with fortran like order
res = arrr.ravel(order = 'F')
print(res)
res.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


(15,)

In [ ]:
#using reshape order to make it one row with 15 values
res = arrr.reshape([1, 15], order = 'F')
print(res)
res.shape
#the shape is (1,15), this does not seem a good solution, the previous two are better

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


(1, 15)

**QUESTION 4**

**Creating 3d from the 2d arr**

In [ ]:
#using reshape method to make it 3d array with each column of the 2d arrr is a dimension of the 3d array
res3d = arrr.reshape(3,1, 5)
print(res3d)
res3d.shape
print(res3d[0])
print("-----------")
print(arrr)
print("------------")
print(arrr[:, 0])

res3d[:,:,0]


[[[ 1  6 11  2  7]]

 [[12  3  8 13  4]]

 [[ 9 14  5 10 15]]]
[[ 1  6 11  2  7]]
-----------
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
------------
[1 2 3 4 5]


array([[ 1],
       [12],
       [ 9]])

In [ ]:
arrr.shape[1]

3

**QUESTION 5**

**Convert 3d arr back to the previous 2d**

In [ ]:
arrBack2d= np.reshape(res3d,(5,3))
print(arrBack2d)
print(arrBack2d.shape)
arrBack2d[: , 0]

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
(5, 3)


array([1, 2, 3, 4, 5])

**QUESTION 6**

**The opposite of intersection ways**

In [ ]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
c = [ element for element in a if element not in b] 
d = [ element for element in b if element not in a] 
type(a)
con = np.concatenate((c, d))
#con is concatenation of the two resulted arrays after only adding the elements that do not exist in the other array
con

array([ 7, 15,  1,  8, 14,  6, 11, 19])

In [ ]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
c = np.setdiff1d(a, b)
d = np.setdiff1d( b , a)
print(c)
print(d)
# con is the same but instead of using list comprehension we used setdiff1d method
con = np.concatenate((c, d))
con
#Note it is ordered here

[ 1  7  8 15]
[ 6 11 14 19]


array([ 1,  7,  8, 15,  6, 11, 14, 19])

**The last question - another attempt with flexible type using genfromtxt:**

In [ ]:
wcNYC = pd.read_csv('/content/Module6_Data.csv')
wcNYC

Year  New York City Population  NYC Consumption(Million gallons per day)  \
0   1979                 7102100.0                                    1512.0   
1   1980                 7071639.0                                    1506.0   
2   1981                 7089241.0                                    1309.0   
3   1982                 7109105.0                                    1382.0   
4   1983                 7181224.0                                    1424.0   
5   1984                 7234514.0                                    1465.0   
6   1985                 7274054.0                                    1326.0   
7   1986                 7319246.0                                    1351.0   
8   1987                 7342476.0                                    1447.0   
9   1988                 7353719.0                                    1484.0   
10  1989                 7344175.0                                    1402.0   
11  1990                 7335650.0                                    1424.0   
12  1991                 7374501.0                                    1469.0   
13  1992                 7428944.0                                    1369.0   
14  1993                 7506166.0                                    1368.5   
15  1994                 7570458.0                                    1357.7   
16  1995                 7633040.0                                    1325.7   
17  1996                 7697812.0                                    1297.9   
18  1997                 7773443.0                                    1205.5   
19  1998                 7858259.0                                    1219.5   
20  1999                 7947660.0                                    1237.2   
21  2000                 8008278.0                                    1240.4   
22  2001                 8024963.5                                    1184.0   
23  2002                 8041649.0                                    1135.6   
24  2003                 8058334.5                                    1093.7   
25  2004                 8075020.0                                    1099.5   
26  2005                 8091705.5                                    1138.0   
27  2006                 8108391.0                                    1069.0   
28  2007                 8125076.5                                    1114.0   
29  2008                 8141762.0                                    1098.0   
30  2009                 8158447.5                                    1007.5   
31  2010                 8175133.0                                    1039.0   
32  2011                 8284098.0                                    1021.0   
33  2012                 8361179.0                                    1009.1   
34  2013                 8422460.0                                    1006.1   
35  2014                 8471990.0                                     996.0   
36  2015                 8516502.0                                    1009.0   
37  2016                 8537673.0                                    1002.0   
38  2017                 8622698.0                                     990.2   

    Per Capita(Gallons per person per day)  
0                                      213  
1                                      213  
2                                      185  
3                                      194  
4                                      198  
5                                      203  
6                                      182  
7                                      185  
8                                      197  
9                                      202  
10                                     191  
11                                     194  
12                                     199  
13                                     184  
14                                     182  
15                                     179  
16                                    

In [ ]:
wcNYC_np = np.genfromtxt("/content/Module6_Data.csv", delimiter=",", dtype=None, names=True)
wcNYC_np

array([(1979, 7102100. , 1512. , 213), (1980, 7071639. , 1506. , 213),
       (1981, 7089241. , 1309. , 185), (1982, 7109105. , 1382. , 194),
       (1983, 7181224. , 1424. , 198), (1984, 7234514. , 1465. , 203),
       (1985, 7274054. , 1326. , 182), (1986, 7319246. , 1351. , 185),
       (1987, 7342476. , 1447. , 197), (1988, 7353719. , 1484. , 202),
       (1989, 7344175. , 1402. , 191), (1990, 7335650. , 1424. , 194),
       (1991, 7374501. , 1469. , 199), (1992, 7428944. , 1369. , 184),
       (1993, 7506166. , 1368.5, 182), (1994, 7570458. , 1357.7, 179),
       (1995, 7633040. , 1325.7, 174), (1996, 7697812. , 1297.9, 169),
       (1997, 7773443. , 1205.5, 155), (1998, 7858259. , 1219.5, 155),
       (1999, 7947660. , 1237.2, 156), (2000, 8008278. , 1240.4, 155),
       (2001, 8024963.5, 1184. , 148), (2002, 8041649. , 1135.6, 141),
       (2003, 8058334.5, 1093.7, 136), (2004, 8075020. , 1099.5, 136),
       (2005, 8091705.5, 1138. , 141), (2006, 8108391. , 1069. , 132),
      

In [ ]:
wcNYC_np['Year']

array([1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989,
       1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017])

In [ ]:
wcNYC_np[1]

(1980, 7071639., 1506., 213)

In [ ]:
wcNYC_np.shape

(39,)

In [ ]:
wcNYC_np[38]

(2017, 8622698., 990.2, 115)

What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [ ]:
wcNYC_np['NYC_ConsumptionMillion_gallons_per_day'].max()

1512.0

In [ ]:
nyc_water['NYC_ConsumptionMillion_gallons_per_day'].max()


In [ ]:
wcNYC_np['Per_CapitaGallons_per_person_per_day'].mean()

160.30769230769232

In [ ]:
np.std(wcNYC_np, axis=0)